name: Run Docker

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
    
jobs:
  job:
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: read
      packages: read

    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        #if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PKGS }}

      - name: Run image
        run: |
          docker pull ghcr.io/looeejee/test-drivers:v1.0
          docker run -e NEO4J_URL=${{ secrets.NEO4J_URL }} \
                -e NEO4J_USERNAME=${{ secrets.NEO4J_USER }} \
                -e NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }} \
                ghcr.io/looeejee/test-drivers:v1.0


