name: CI - Test Drivers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      NEO4J_URL:
        description: 'Neo4J URL'
        required: false
        default: ''
      NEO4J_USER:
        description: 'Neo4J User'
        required: false
        default: ''
      NEO4J_PASSWORD:
        description: 'Neo4J Password'
        required: false
        default: ''
      PYTHON_VERSION:
        description: 'Python version to use'
        required: false
        default: '3.11'  # Default Python version
      NEO4J_DRIVER_VERSION:
        description: 'Neo4J Python Driver version to use'
        required: false
        default: '5.27.0'  # Default Python version

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Ceckout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            python-driver

      # Runs a single command using the runners shell
      - name: Test Python Drivers
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.PYTHON_VERSION }}  # Use the input for Python 
      
      # Install dependencies
      - name: Install dependencies
        run: pip install python-dotenv neo4j==${{ github.event.inputs.NEO4J_DRIVER_VERSION }}

      - name: Run Tests
        env:
          NEO4J_URI: ${{ github.event.inputs.NEO4J_URL || secrets.NEO4J_URL }}
          NEO4J_USERNAME: ${{ github.event.inputs.NEO4J_USER || secrets.NEO4J_USER }}
          NEO4J_PASSWORD: ${{ github.event.inputs.NEO4J_PASSWORD || secrets.NEO4J_PASSWORD }}
        run: python $PWD/main.py